name: Mirror to GitLab

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git push https://oauth2:${{ secrets.GITLAB_TOKEN }}@git.uysm.org/openllmbench/trainbench.git HEAD:github-mirror --tags